### ISSUE TITLE
好像不是很高效

### ISSUE THREAD

**Issue by ugksoft** [linghuazaii/Charles-Server#1]
好像不是很高效, 锁不应该用mux,而是多用spin, 创建那么多线程,没考虑过CPU的感受,上下切换很费时间的
8核时,所有线程应该就只有8个,或是7个(留一个给系统),每个线程指定所属CPU

处理数据,肯定占大头,比如接收到数据包,解压,分析,再压缩了丢给缓冲列表, 由一个发送线程,把这些缓冲发出去

这样,就需要有一个缓冲池,

而销毁句柄(如关闭sock),这些大多数情况下瞬即完成的,由线程频繁切换去销毁,不划算,应该异步,比如每5-50ms清理一次

总的来说,你这个模式, 离C10M相当遥远, 撑死了C10K模式

---------------------
(平常Windows,偶尔要写个Linux下高并发程序,所以网上找找架构帮自己理清头绪,看到你的代码,回了一下)

**Comment by linghuazaii** [comment]
在理，但是我不会用spinlock，太耗CPU，和CPU绑定我觉得对与运算类的程序可以考虑，偏io的其实差别不大，这个就当是个练手的例子吧，没法应用到大项目，感兴趣可以看看nginx源码。

**Comment by ugksoft** [comment]
spin只有2-3个汇编指令, 是CPU原生支持的,我试过,循环锁1M次,ms级别
具体看应用吧, 不过高并发,线程和CPU配合下,必然是spin的,spin的缺点是,卡着主线程了
两组线程有独立数据时,不能根据CPU线程,让1-4个线程用SpinA, 5-8用SpinB 而mux可以


结贴吧

**Comment by linghuazaii** [comment]
就算是线程池你也要用spin lock吗？

**Comment by linghuazaii** [comment]
建议了解下linux任务调度的机制和futex
